# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "learn-app"
client_id = "02f88aa21b69dd518208da183e79096b"
application_url = "https://2e00-103-138-250-193.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://2e00-103-138-250-193.ngrok-free.app/auth/callback",
  "https://2e00-103-138-250-193.ngrok-free.app/auth/shopify/callback",
  "https://2e00-103-138-250-193.ngrok-free.app/api/auth/callback",
  "https://2e00-103-138-250-193.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "learn-app-product.myshopify.com"
